Working factorial. **Only works with a right operand. Right operand i…
maddypie/PyCalc pull request #19
Opened 2020-10-31 21:51 UTC by nathdilla

…s disregarded.

2020-11-02 18:51 UTC, maddypie requested changes
You did a great job. :+1:  
Try to make as many changes/corrections yourself. I will also be working on this code.

2020-11-02 18:51 UTC, maddypie commented on core_logic.py
> +    __operators: list = ['(', '^', '/', '*', '+', '-', 'x!']
Comply to BODMAS rule. Insert the factorial in index 1.

2020-11-02 18:51 UTC, maddypie commented on core_logic.py
> +            'x!': lambda x, y: Calculate.factorial(None,int(x),int(y)),
Using `math.factorial` will be a better way to do it.

2020-11-02 18:51 UTC, maddypie commented on core_logic.py
> +        print(result)
Remove debug-print statements.

2020-11-02 18:51 UTC, maddypie commented on core_logic.py
> +        print(result)
Can be replaced with `math.factorial`.

2020-11-02 18:51 UTC, maddypie commented on core_logic.py
> +        if any(fact_op):
Missed to form a *generator* for `fact_op`. See line 69 for reference.

2020-11-02 18:51 UTC, maddypie commented on storage.py
> +    __operators: list = ['x!','^', '/', '*', '+', '-']
Don't mix operand `x` and operator `x`. Here `__operator` list contains only operators.

2020-11-02 18:52 UTC, maddypie commented
It is **awesome of you** to contribute to this project. I really appreciate your work. You have made some notable lead to advanced-mode-factorial feature. :smile: :+1: 

As to your PR:
 1. Did you run the program from your side to check if it is working. The code you have added breaks the earlier code (view unittest-`checks` in this PR, it fails). If you need to, try refactoring the original code to accomodate your ideas/implementations.
 2.  Do add *unittest* to support your code. Adding unittests are simple. 
 3. Stick to [PEP8](https://www.python.org/dev/peps/pep-0008/).
 4. Add/Edit documentation whenever possible.

Try your best to get the `checks` passing. I will also be editting this PR to get it working. I have reviewed your PR, please go throught it also.  
Please feel free to ping this thread for any clarifications.

2020-12-23 05:01 UTC, maddypie commented
Please have a look at branch **unary** for the changes taking place.

2021-03-14 16:42 UTC, tsadarsh commented
Pymanujan v2.0 is finally released :partying_face:!!
Many new operators are added. Factorial is all good now.
Thank you for participating :smile:

2021-03-14 16:42 UTC, closed without merging